annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.1
description: diffwatcher is a Kubernetes Difference watcher that currently publishes notification to needed channels. Run it in your k8s cluster, and you will get event notifications in a configured channels.
home: https://github.com/marvasgit/kubernetes-diffwatcher
icon: https://github.com/marvasgit/kubernetes-diffwatcher/docs/diffwatcher-logo-240.png
keywords:
- kubernetes
- slack
- hipchat
- mattermost
- flock
- msteams
maintainers: []
name: diffwatcher
sources:
- https://github.com/marvasgit/kubernetes-diffwatcher
version: 1.0.1
